nodeLinker: node-modules

packageExtensions:
  "@types/react-dom@*":
    peerDependencies:
      "@types/react": "18.2.45" # Match the version specified for @types/react
  # 他のライブラリが異なるReactバージョンを要求している場合、ここに追加
  # 例:
  # "some-library@*":
  #   peerDependencies:
  #     react: "18.2.0"
