import { CustomApiProvider, SystemPromptMode, CustomApiConfig } from '../src/services/user-config'

// CustomApiConfig をベースにプリセット型を作成（保存時にユーザが埋める項目は除外）
type PresetFromConfig = Omit<CustomApiConfig, 'apiKey' | 'enabled' | 'webAccess' | 'id'>

const apiPresets = {
  version: '1.0.0',
  description: 'API provider presets configuration',
  settings: {
    enableCompanyPresets: false,
    showPerplexityTemplate: false,
  },
  presets: {
    OpenAI: {
      name: 'OpenAI',
      shortName: 'GPT',
      model: 'gpt-5',
      host: 'https://api.openai.com',
      isHostFullPath: false,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'OpenAI.Green',
      thinkingMode: true,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    Anthropic: {
      name: 'Anthropic',
      shortName: 'Claud',
      model: 'claude-sonnet-4-5',
      host: 'https://api.anthropic.com/',
      isHostFullPath: false,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'Claude.Orange',
      thinkingMode: true,
      thinkingBudget: 8000,
      provider: CustomApiProvider.Anthropic,
    },

    Gemini: {
      name: 'Google Gemini',
      shortName: 'G Gemin',
      model: 'gemini-2.5-pro',
      host: 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
      isHostFullPath: true,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'Gemini.Color',
      thinkingMode: true,
      thinkingBudget: 8000,
      provider: CustomApiProvider.GeminiOpenAI,
    },

    DeepSeek: {
      name: 'DeepSeek',
      shortName: 'DS',
      model: 'deepseek-chat',
      host: 'https://api.deepseek.com/',
      isHostFullPath: false,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'deepseek',
      thinkingMode: false,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    Grok: {
      name: 'Grok',
      shortName: 'Grok',
      model: 'grok-4',
      host: 'https://api.x.ai/v1',
      isHostFullPath: false,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'grok',
      thinkingMode: false,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    DeepInfra: {
      name: 'DeepInfra',
      shortName: 'DI',
      model: 'deepseek-ai/DeepSeek-V3.1',
      host: 'https://api.deepinfra.com/v1/openai/chat/completions',
      isHostFullPath: true,
      temperature: 0.7,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'OpenAI.Blue',
      thinkingMode: true,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    Fireworks: {
      name: 'Fireworks AI',
      shortName: 'Fire',
      model: 'accounts/fireworks/models/qwen3-coder-480b-a35b-instruct',
      host: 'https://api.fireworks.ai/inference/v1',
      isHostFullPath: false,
      temperature: 0.6,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'OpenAI.Red',
      thinkingMode: false,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },

    QwenCoder: {
      name: 'Qwen Coder',
      shortName: 'QwCod',
      model: 'qwen3-coder-plus',
      host: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
      isHostFullPath: false,
      temperature: 0.3,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'qianwen',
      thinkingMode: false,
      thinkingBudget: 2000,
      provider: CustomApiProvider.QwenOpenAI,
    },

    OpenRouter: {
      name: 'OR DeepSeek V3.1 free',
      shortName: 'ORDS V3.1',
      model: 'deepseek/deepseek-chat-v3.1:free',
      host: 'https://openrouter.ai/api/v1',
      isHostFullPath: false,
      temperature: 1,
      systemMessage: '',
      systemPromptMode: SystemPromptMode.COMMON,
      avatar: 'deepseek',
      thinkingMode: false,
      thinkingBudget: 2000,
      provider: CustomApiProvider.OpenAI,
    },
  } satisfies Record<string, PresetFromConfig>,
  companyPresets: {},
}

export default apiPresets